steps:
  - name: build
    image: golang:1.25
    commands:
      - cd agent && go build ./...

  - name: test
    image: golang:1.25
    commands:
      - cd agent && go test ./...
      - cd shared && go test ./...
