apiVersion: v1
kind: ServiceAccount
metadata:
  name: neverland
  namespace: tink-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neverland
rules:
  - apiGroups: ["tinkerbell.org"]
    resources: ["hardware", "templates", "workflows"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["bmc.tinkerbell.org"]
    resources: ["machines", "jobs", "tasks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neverland
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neverland
subjects:
  - kind: ServiceAccount
    name: neverland
    namespace: tink-system
